# Generated by Django 4.0.4 on 2022-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_serials_box_office_alter_serials_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='details',
            field=models.CharField(max_length=500),
        ),
    ]
