# Generated by Django 4.0.4 on 2022-05-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0005_alter_imagesserial_serial_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='details',
            field=models.TextField(),
        ),
    ]
