# Generated by Django 4.0.4 on 2022-05-17 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0006_alter_serials_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesserial',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='serials.serials'),
        ),
    ]
