# Generated by Django 4.0.4 on 2022-05-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0007_alter_imagesserial_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serials',
            name='main_image',
            field=models.ImageField(default='No image', upload_to=''),
        ),
    ]
