# Generated by Django 4.0.4 on 2022-05-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0011_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='serials',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serials.genres'),
        ),
    ]
